### ISSUE TITLE
Missing Lecture notes

### ISSUE THREAD

**Issue by gomahajan** [nadia-polikarpova/cse291-program-synthesis#1]
Where can I find the lecture slides?

https://github.com/nadia-polikarpova/cse291-program-synthesis/blob/dc14355115e73e59128bb11951b93905fead1608/README.md#L6

**Comment by nadia-polikarpova** [comment]
Slides for Lecture 1 are now in the repository and linked from the syllabus page. In the future, the slides will be posted after the lecture.
