### ISSUE TITLE
Searching for teammates

### ISSUE THREAD

**Issue by nadia-polikarpova** [nadia-polikarpova/cse291-program-synthesis#10]
If anyone is searching for project teammates, post a comment to this issue!

**Comment by greatEncoder** [comment]
I am looking for a partner. I am a Masters student in CS and could meet Mondays, Wednesdays, Thursday Mornings, and Weekends. I am open to discuss on the projects to work on and quite comfortable with several different programming languages. I have done similar courses and have written few research style papers. If you are interested partnering up I could also meet to talk more details.

**Comment by KasraF** [comment]
Hey @greatEncoder and all!

I'm a CS Master's student looking for a partner (or two!) for the project. I'm fairly familiar with programming languages (I took undergrad PL and Compilers and a grad level PL design course, I've also TAed CSE131), and my schedule is fairly flexible (I'm only busy MF 3-4, TTh 12-5, and W [9:30, 10:30] U [3, 4]).

If anyone's interested, please contact me at kferdows@ucsd.edu and we can find time to meet and talk project ideas.

Thanks!

**Comment by taineleau** [comment]
Hey there!

Updated: already teamed up with two other students!

I'm a first-year student working on NLP and ML. I am looking for a partner (or two) who is super, super interested in program synthesis and machine learning. I would prefer to do a project on using program synthesis technique for ML (like Nadia's EMNLP [paper](https://cseweb.ucsd.edu/~npolikarpova/publications/emnlp19.pdf)). As a non-typical AI-track Ph.D., I interned at NVIDIA's computing architecture group and was the head TA of an undergrad level compiler course. 

I am free the whole day MWF and 10-3 TTh. 

If anyone is interested, shoot me an email at danlu@ucsd.edu or stop by at CSE 3242.

Thank you!

**Comment by enjhnsn2** [comment]
Hey,
I'm a first year PhD student working on Systems Security + Program Analysis. I am free to work pretty much any day of the week. 
I have a very concrete project idea in mind for an application of program synthesis to embedded system security. 
Let me know if you are interested at e5johnso@eng.ucsd.edu .

**Comment by priyanmuthu** [comment]
Hi,
I'm a second-year Master's student. My primary area of research is HCI + PL. Prior to this I worked as a research fellow at MSR. You can know more about me here: https://priyan.info. 
If you are interested, email me at pvaithil@eng.ucsd.edu. I'm free to work any day of the week.

**Comment by JLucsd** [comment]
Hi,
I am Jiaxiang Liang, a second-year master student. I do not have something particular in mind for the project yet, and I am open to discuss any project idea. Also, my schedule is flexible.

Email me at jil773@ucsd.edu.
