### ISSUE TITLE
Looking for Teammate

### ISSUE THREAD

**Issue by gamero** [nadia-polikarpova/cse291-program-synthesis#2]
Hi! I'm a third-year PhD student in Networking and Security, and looking for a teammate for this class. I am open to any project ideas on any topic, though would prefer to work on networking or security if at all possible. You can reach me at agamerog@eng.ucsd.edu.
Thanks!
-Alex

**Comment by gomahajan** [comment]
Hey Alex, Are you also taking CSE291- Automated Reasoning? I am thinking of doing a joint project with Automated Reasoning.

Thanks!
Gaurav
First-Year PhD, CSE
gmahajan@eng.ucsd.edu

**Comment by metakirby5** [comment]
I don't want to spam the issues list, so I'll also post my "Looking for Teammate" ad here.

I'm a first year MS student (BS/MS). Living at home, but am coming to school Mon-Thu, so I can come earlier/stay later to meet. Experienced in full stack web dev and machine learning, but flexible to learn anything.

Email: e1chan@eng.ucsd.edu
Resume: https://metakirby5.github.io/resume/

Thanks,
-Ethan

EDIT: I found a partner :)

**Comment by aaronguo1996** [comment]
Hi! I'm a first year master student and I am looking for a teammate for this class. I am open to any topic but prefer to do some research about program analysis or verification. And I am willing to learn anything.

Thanks,
Aaron
zhg069@ucsd.edu

**Comment by souravan** [comment]
Hi, I am first year master student. I am looking for a teammate for the project. I am interested in computer systems and security mostly but would be willing to work on projects related to other areas as well. I have some amount of experience with program analysis and verification.

Thanks,
Sourav
s9anand@ucsd.edu

**Comment by asbjornlystrup** [comment]
Hi, I just recently joined the course because of some trouble I had with enrollment. I'm looking for a teammate. I'm an exchange student in my 4th year as part of a 5 year master program. My specialization is in algorithms and computers, but I'm up for pretty much any project.

Please send me a mail if you're interested in working together.

Thank you,
Asbjoern Lystrup
asbjorn.lystrup@gmail.com

Edit:
I found a teammate :)
