### ISSUE TITLE
prerequisite

### ISSUE THREAD

**Issue by HaoyangFan** [nadia-polikarpova/cse291-program-synthesis#5]
So for the CSE 291 that will be offered in Fall 2018, I can see that it has the prerequisite as "CSE 230". I am an incoming graduate student and I already took CSE 130(undergraduate version of CSE 230) at UCSD. So am I considered to be eligible to be enrolled in this class? 

For the programming background: I learn OCaml from CSE 130 and I personally use Haskell before

Thanks:blush:

**Comment by metakirby5** [comment]
Fwiw, I was a past student in your situation and I was enrolled without issue.

**Comment by HaoyangFan** [comment]
@metakirby5  Thanks for sharing the info. Now I just wait for the instructor's confirmation

**Comment by nadia-polikarpova** [comment]
130 should be enough. Sorry for a delayed reply.
