### ISSUE TITLE
FlashFill Paper Review not Assigned on EasyChair

### ISSUE THREAD

**Issue by eh-dub** [nadia-polikarpova/cse291-program-synthesis#8]
**Expected Behaviour**: FlashFill paper is listed under "Reviews -> Assigned to me"
**Actual Behaviour**: FlashFill paper is not listed under "Reviews -> Assigned to me"

I'm not sure if it hasn't been assigned to just me or the entire class. 
I attached a screenshot in case that's helpful.

<img width="1440" alt="screen shot 2018-10-16 at 8 16 00 am" src="https://user-images.githubusercontent.com/846035/47027152-c25d0b80-d11b-11e8-87e2-d694b7f8c1b8.png">

**Comment by nadia-polikarpova** [comment]
Thanks for the reminder! Indeed, I forgot to assign the paper this week. Fixed now.
