### ISSUE TITLE
Submitting Proposal?

### ISSUE THREAD

**Issue by michaelbjames** [nadia-polikarpova/cse291-program-synthesis#9]
To where should we submit our proposal?

**Comment by davidmrdavid** [comment]
This was not in the wiki, but the slides suggest that we need to do it in the Google Drive. Hope others find this issue helpful though. I think we can close this ticket

**Comment by nadia-polikarpova** [comment]
Upload to the Proposals folder in the GDrive. Can be a pdf or gdoc. File name should be Team-N.
This info was in the Tuesday's lecture, as David pointed out.
